CREATE TABLE Point (
  ID INTEGER PRIMARY KEY,
  X INTEGER NOT NULL,
  Y INTEGER NOT NULL  
);

CREATE TABLE LocalMap (
  ID INTEGER PRIMARY KEY,
  Name CHAR(64) NOT NULL,
  LeftID INTEGER NOT NULL,
  RightID INTEGER NOT NULL, 
  FOREIGN KEY(LeftID) REFERENCES Point(ID),
  FOREIGN KEY(RightID) REFERENCES Point(ID)
);

CREATE TRIGGER TR_LocalMap_Delete
AFTER DELETE ON LocalMap
FOR EACH ROW
BEGIN
    DELETE FROM Point WHERE ID in (OLD.LeftID, OLD.RightID);
END;

CREATE TABLE MapLevel (
  ID INTEGER PRIMARY KEY,
  MapID INTEGER NOT NULL,
  Level INTEGER NOT NULL,
  Picture BINARY,
  FOREIGN KEY(MapID) REFERENCES LocalMap(ID) ON DELETE CASCADE
);


