CREATE TABLE Point (
  ID INTEGER PRIMARY KEY,
  X INTEGER NOT NULL,
  Y INTEGER NOT NULL  
);

CREATE TABLE [LocalMap](
  [ID] INTEGER PRIMARY KEY, 
  [Name] CHAR(64) NOT NULL, 
  [Picture] BINARY, 
  [Left] INTEGER NOT NULL, 
  [Top] INTEGER NOT NULL, 
  [Right] INTEGER NOT NULL, 
  [Bottom] INTEGER NOT NULL
);

CREATE TABLE MapLevel (
  ID INTEGER PRIMARY KEY,
  MapID INTEGER NOT NULL,
  Level INTEGER NOT NULL,
  Name CHAR(64) NOT NULL,
  Picture BINARY,
  FOREIGN KEY(MapID) REFERENCES LocalMap(ID) ON DELETE CASCADE
);

CREATE TABLE Marker (
  [ID] INTEGER PRIMARY KEY,
  [MapID] INTEGER NOT NULL,
  [Name] CHAR(64) NOT NULL,
  [Kind] INTEGER NOT NULL,
  [Left] INTEGER NOT NULL,
  [Top] INTEGER NOT NULL,
  FOREIGN KEY(MapID) REFERENCES LocalMap(ID) ON DELETE CASCADE
);

